doctrine:
    dbal:
        url: "%env(resolve:DATABASE_URL)%"

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: attribute
                dir: "%kernel.project_dir%/src/Entity"
                prefix: 'App\Entity'
                alias: App
        dql:
            string_functions:
                clearstr: App\Helpers\ClearStrFunction
                SIMILARITY_DIST: App\Doctrine\Functions\SimilarityDistFunction
                STRICT_WORD_SIMILARITY_COMMUTATOR_OP: App\Doctrine\Functions\StrictWordSimilarityCommutatorOpFunction
            numeric_functions:
                Random: App\Doctrine\DBAL\FunctionNode\Random
