oneup_flysystem:
  adapters:
    default_adapter:
      awss3v3:
        client: Aws\S3\S3Client
        bucket: '%env(AWS_S3_BUCKET_NAME)%'
  filesystems:
    default_filesystem:
      adapter: default_adapter