controllers:
    resource: ../../src/Controller/
    type: annotation

secure_controllers:
    resource: ../../src/Controller/Secure/
    type: annotation
    prefix: /secure

kernel:
    resource: ../../src/Kernel.php
    type: annotation
