# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    images_directory: '%kernel.project_dir%/public/uploads/images'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    App\Helpers\FileUploader:
        arguments:
            $targetDirectory: '%images_directory%'
    
    Aws\S3\S3Client:
        arguments:
            -   
                version: 'latest'
                region: '%env(AWS_S3_BUCKET_REGION)%'
                credentials:
                    key: '%env(AWS_S3_ACCESS_ID)%'
                    secret: '%env(AWS_S3_ACCESS_SECRET)%'
    
    League\Flysystem\FilesystemInterface:  '@oneup_flysystem.default_filesystem_filesystem'

    intervention.image_manager:
        class: Intervention\Image\ImageManager
        public: false

    App\Controller\Secure\ProductsController:
        arguments:
            $imageManager: '@intervention.image_manager'